### ISSUE TITLE
Puppet issue

### ISSUE THREAD

**Issue by xakaitetoia** [lefred/percona-cluster#4]
Even if you download another centos 6.3 box i still got the below error when the provisioning starts with puppet

The `puppet` binary appears not to be in the PATH of the guest. This
could be because the PATH is not properly setup or perhaps Puppet is not
installed on this guest. Puppet provisioning can not continue without
Puppet properly installed.

Also somehow i run again the vagrant provision percona1 command and now i got a bunch of errors

$ vagrant provision percona1
==> percona1: Running provisioner: puppet...
==> percona1: Running Puppet with site.pp...
==> percona1: Info: Loading facts
==> percona1: Info: Scope(Class[Percona::Cluster::Packages]): Congrats ! Using 5.6 !!
==> percona1: Warning: Variable access via 'hostname' is deprecated. Use '@hostname' instead. template[/tmp/vagrant-puppet/modules-3088a94ea8a466aaa1be47064232ab53/percona/templates/cluster/my.cnf.erb]:4
==> percona1:    (at /usr/lib/ruby/site_ruby/1.8/puppet/parser/templatewrapper.rb:77:in `method_missing')
==> percona1: Notice: Compiled catalog for percona1 in environment production in 0.74 seconds
==> percona1: Info: Applying configuration version '1549540331'
==> percona1: Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install Percona-XtraDB-Cluster-server-56.x86_64' returned 1: Error: Package: Percona-XtraDB-Cluster-galera-3-3.30-1.el6.x86_64 (percona)
==> percona1:            Requires: libssl.so.10(libssl.so.10)(64bit)
==> percona1: Error: Package: 1:Percona-XtraDB-Cluster-client-56-5.6.42-28.30.1.el6.x86_64 (percona)
==> percona1:            Requires: libcrypto.so.10(libcrypto.so.10)(64bit)
==> percona1: Error: Package: 1:Percona-XtraDB-Cluster-shared-56-5.6.42-28.30.1.el6.x86_64 (percona)
==> percona1:            Requires: libssl.so.10(libssl.so.10)(64bit)
==> percona1: Error: Package: 1:Percona-XtraDB-Cluster-server-56-5.6.42-28.30.1.el6.x86_64 (percona)
==> percona1:            Requires: libssl.so.10(libssl.so.10)(64bit)
==> percona1: Error: Package: percona-xtrabackup-2.3.10-1.el6.x86_64 (percona)
==> percona1:            Requires: libev.so.4()(64bit)
==> percona1: Error: Package: 1:Percona-XtraDB-Cluster-server-56-5.6.42-28.30.1.el6.x86_64 (percona)
==> percona1:            Requires: libcrypto.so.10(libcrypto.so.10)(64bit)
==> percona1: Error: Package: 1:Percona-XtraDB-Cluster-shared-56-5.6.42-28.30.1.el6.x86_64 (percona)
==> percona1:            Requires: libcrypto.so.10(OPENSSL_1.0.1_EC)(64bit)
==> percona1: Error: Package: Percona-XtraDB-Cluster-galera-3-3.30-1.el6.x86_64 (percona)
==> percona1:            Requires: libcrypto.so.10(libcrypto.so.10)(64bit)
==> percona1: Error: Package: 1:Percona-XtraDB-Cluster-server-56-5.6.42-28.30.1.el6.x86_64 (percona)
==> percona1:            Requires: libz.so.1(ZLIB_1.2.0)(64bit)
==> percona1: Error: Package: percona-xtrabackup-2.3.10-1.el6.x86_64 (percona)
==> percona1:            Requires: libssl.so.10(libssl.so.10)(64bit)
==> percona1: Error: Package: Percona-XtraDB-Cluster-galera-3-3.30-1.el6.x86_64 (percona)
==> percona1:            Requires: libcrypto.so.10(OPENSSL_1.0.1_EC)(64bit)
==> percona1: Error: Package: 1:Percona-XtraDB-Cluster-shared-56-5.6.42-28.30.1.el6.x86_64 (percona)
==> percona1:            Requires: libcrypto.so.10(libcrypto.so.10)(64bit)
==> percona1: Error: Package: 1:Percona-XtraDB-Cluster-server-56-5.6.42-28.30.1.el6.x86_64 (percona)
==> percona1:            Requires: socat
==> percona1: Error: Package: 1:Percona-XtraDB-Cluster-server-56-5.6.42-28.30.1.el6.x86_64 (percona)
==> percona1:            Requires: libcrypto.so.10(OPENSSL_1.0.1_EC)(64bit)
==> percona1: Error: Package: 1:Percona-XtraDB-Cluster-client-56-5.6.42-28.30.1.el6.x86_64 (percona)
==> percona1:            Requires: libssl.so.10(libssl.so.10)(64bit)
==> percona1: Error: Package: percona-xtrabackup-2.3.10-1.el6.x86_64 (percona)
==> percona1:            Requires: libz.so.1(ZLIB_1.2.0)(64bit)
==> percona1: Error: Package: 1:Percona-XtraDB-Cluster-client-56-5.6.42-28.30.1.el6.x86_64 (percona)
==> percona1:            Requires: libcrypto.so.10(OPENSSL_1.0.1_EC)(64bit)
==> percona1: Error: Package: percona-xtrabackup-2.3.10-1.el6.x86_64 (percona)
==> percona1:            Requires: libcrypto.so.10(libcrypto.so.10)(64bit)
==> percona1:  You could try using --skip-broken to work around the problem
==> percona1:  You could try running: rpm -Va --nofiles --nodigest
==> percona1: Error: /Stage[main]/Percona::Cluster::Packages/Package[Percona-XtraDB-Cluster-server-56.x86_64]/ensure: change from absent to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y install Percona-XtraDB-Cluster-server-56.x86_64' returned 1: Error: Package: Percona-XtraDB-Cluster-galera-3-3.30-1.el6.x86_64 (percona)
==> percona1:            Requires: libssl.so.10(libssl.so.10)(64bit)
==> percona1: Error: Package: 1:Percona-XtraDB-Cluster-client-56-5.6.42-28.30.1.el6.x86_64 (percona)
==> percona1:            Requires: libcrypto.so.10(libcrypto.so.10)(64bit)
==> percona1: Error: Package: 1:Percona-XtraDB-Cluster-shared-56-5.6.42-28.30.1.el6.x86_64 (percona)
==> percona1:            Requires: libssl.so.10(libssl.so.10)(64bit)
==> percona1: Error: Package: 1:Percona-XtraDB-Cluster-server-56-5.6.42-28.30.1.el6.x86_64 (percona)
==> percona1:            Requires: libssl.so.10(libssl.so.10)(64bit)
==> percona1: Error: Package: percona-xtrabackup-2.3.10-1.el6.x86_64 (percona)
==> percona1:            Requires: libev.so.4()(64bit)
==> percona1: Error: Package: 1:Percona-XtraDB-Cluster-server-56-5.6.42-28.30.1.el6.x86_64 (percona)
==> percona1:            Requires: libcrypto.so.10(libcrypto.so.10)(64bit)
==> percona1: Error: Package: 1:Percona-XtraDB-Cluster-shared-56-5.6.42-28.30.1.el6.x86_64 (percona)
==> percona1:            Requires: libcrypto.so.10(OPENSSL_1.0.1_EC)(64bit)
==> percona1: Error: Package: Percona-XtraDB-Cluster-galera-3-3.30-1.el6.x86_64 (percona)
==> percona1:            Requires: libcrypto.so.10(libcrypto.so.10)(64bit)
==> percona1: Error: Package: 1:Percona-XtraDB-Cluster-server-56-5.6.42-28.30.1.el6.x86_64 (percona)
==> percona1:            Requires: libz.so.1(ZLIB_1.2.0)(64bit)
==> percona1: Error: Package: percona-xtrabackup-2.3.10-1.el6.x86_64 (percona)
==> percona1:            Requires: libssl.so.10(libssl.so.10)(64bit)
==> percona1: Error: Package: Percona-XtraDB-Cluster-galera-3-3.30-1.el6.x86_64 (percona)
==> percona1:            Requires: libcrypto.so.10(OPENSSL_1.0.1_EC)(64bit)
==> percona1: Error: Package: 1:Percona-XtraDB-Cluster-shared-56-5.6.42-28.30.1.el6.x86_64 (percona)
==> percona1:            Requires: libcrypto.so.10(libcrypto.so.10)(64bit)
==> percona1: Error: Package: 1:Percona-XtraDB-Cluster-server-56-5.6.42-28.30.1.el6.x86_64 (percona)
==> percona1:            Requires: socat
==> percona1: Error: Package: 1:Percona-XtraDB-Cluster-server-56-5.6.42-28.30.1.el6.x86_64 (percona)
==> percona1:            Requires: libcrypto.so.10(OPENSSL_1.0.1_EC)(64bit)
==> percona1: Error: Package: 1:Percona-XtraDB-Cluster-client-56-5.6.42-28.30.1.el6.x86_64 (percona)
==> percona1:            Requires: libssl.so.10(libssl.so.10)(64bit)
==> percona1: Error: Package: percona-xtrabackup-2.3.10-1.el6.x86_64 (percona)
==> percona1:            Requires: libz.so.1(ZLIB_1.2.0)(64bit)
==> percona1: Error: Package: 1:Percona-XtraDB-Cluster-client-56-5.6.42-28.30.1.el6.x86_64 (percona)
==> percona1:            Requires: libcrypto.so.10(OPENSSL_1.0.1_EC)(64bit)
==> percona1: Error: Package: percona-xtrabackup-2.3.10-1.el6.x86_64 (percona)
==> percona1:            Requires: libcrypto.so.10(libcrypto.so.10)(64bit)
==> percona1:  You could try using --skip-broken to work around the problem
==> percona1:  You could try running: rpm -Va --nofiles --nodigest
==> percona1: Notice: /Stage[main]/Percona::Cluster::Config/File[/etc/my.cnf]: Dependency Package[Percona-XtraDB-Cluster-server-56.x86_64] has failures: true
==> percona1: Warning: /Stage[main]/Percona::Cluster::Config/File[/etc/my.cnf]: Skipping because of failed dependencies
==> percona1: Notice: /Stage[main]/Percona::Cluster::Config/Exec[disable-selinux]: Dependency Package[Percona-XtraDB-Cluster-server-56.x86_64] has failures: true
==> percona1: Warning: /Stage[main]/Percona::Cluster::Config/Exec[disable-selinux]: Skipping because of failed dependencies
==> percona1: Notice: /Stage[main]/Percona::Cluster::Service/Service[mysql]: Dependency Package[Percona-XtraDB-Cluster-server-56.x86_64] has failures: true
==> percona1: Warning: /Stage[main]/Percona::Cluster::Service/Service[mysql]: Skipping because of failed dependencies
==> percona1: Notice: Finished catalog run in 2.26 seconds

**Comment by lefred** [comment]
Hi, 
this code is not more maintained and is there for overview purpose only.
